### ISSUE TITLE
when using PathFinder the files should preserve their alphabetical order

### ISSUE THREAD

**Issue by almoehi** [ground5hark/sbt-concat#14] opened 2014-11-13 19:59 UTC
On line 57 the collected files are converted to a Map:
```
(groupName, r.toMap.values)
```
this results in unpredictable order of concatenation of the matched files and eventually results in JS errors.

The files should be concatenated in their natural (e.g. alphabetical) order - isn't it possible to use the value of ```r```directly ?

**Comment by LMnet** [comment] 2015-07-15 08:05
I'm pretty sure that natural order is not expected behavior. If you want to concat some files in special order, I believe that best way is to use order from the `group` mapping (I mean from `Concat.groups` task in the user's build file). Right now `toMap` method brakes the ordering, so we change this to something else. I will try to do this, because I really need it in my build.

**Comment by ground5hark** [comment] 2015-12-11 00:39
Merged the wrong ordering fix, reopening

**Closed** 2015-12-11 00:45 UTC

**Comment by almoehi** [comment] 2017-05-21 20:28
I am pretty sure that this IS the expected behaviour. If I want some weired / special ordering I agree, that one should explicitly define the ordering by listing each file in the Concat.groups task.

However, if you use wildcards the expected behavious is the same as when you use wildcards on your OS e.g. `ls -l *.js`. I have tons of JS files (UI engineers keep adding & removing some) and I don't want to list all of them manually in the Concat.groups.

Layout in the file system (ls javascripts/myapp/ui/metis/core/*.js):
```
00-metis.js
01-fullscreen.js
02-ie-emulation-modes-warning.js
03-ie10-viewport-bug-workaround.js
04-metisMenuAnimatePanel.js
05-metisMenu.js
06-metisNavBar.js
```

build.sbt setting used:
```
"metis-core.js" -> group(((sourceDirectory in Assets).value / "javascripts" / "myapp" / "ui" / "metis" / "core" ) * "*.js")
```

ordering in the concatenated file what sbt-concat produces:
```
/** javascripts/myapp/ui/metis/core/00-metis.js **/
/** javascripts/myapp/ui/metis/core/06-metisNavBar.js **/
/** javascripts/myapp/ui/metis/core/05-metisMenu.js **/
/** javascripts/myapp/ui/metis/core/04-metisMenuAnimatePanel.js **/
/** javascripts/myapp/ui/metis/core/01-fullscreen.js **/
/** javascripts/myapp/ui/metis/core/03-ie10-viewport-bug-workaround.js **/
/** javascripts/myapp/ui/metis/core/02-ie-emulation-modes-warning.js **/
```

There is absolutly no obvious way how this ordering comes about and how to influence it by renaming files.

Expected behavious should be the ordering you see in your IDE or when doing "ls -l".

**Comment by slavaschmidt** [comment] 2019-04-05 09:05
This would be a nice feature indeed. It would be infinitely better to have at least this kind of an expectation about the grouping result as opposed to the impossibility to have any expectations at all. 

Sad to see how a PR implementing this was merged but then removed. I observe a meaningful opinion just dismissed without stating what an expected behaviour should be.

👎
